# Common environment variables for all workflows
# These can be overridden by API calls with dynamic values
# Proper handling of API data with null/default values for optional fields
environment: &default_env
  flutter: stable
  xcode: latest
  cocoapods: default
  vars:
    # App Configuration - Required from API
    VERSION_NAME: "${VERSION_NAME}"
    VERSION_CODE: "${VERSION_CODE}"
    APP_NAME: "${APP_NAME}"
    ORG_NAME: "${ORG_NAME}"
    WEB_URL: "${WEB_URL}"
    PKG_NAME: "${PKG_NAME}"
    BUNDLE_ID: "${BUNDLE_ID}"
    EMAIL_ID: "${EMAIL_ID}"

    # Feature Flags - API configurable with proper defaults
    PUSH_NOTIFY: "${PUSH_NOTIFY}"
    IS_CHATBOT: "${IS_CHATBOT}"
    IS_DEEPLINK: "${IS_DEEPLINK}"
    IS_SPLASH: "${IS_SPLASH}"
    IS_PULLDOWN: "${IS_PULLDOWN}"
    IS_BOTTOMMENU: "${IS_BOTTOMMENU}"
    IS_LOAD_IND: "${IS_LOAD_IND}"

    # Assets - API configurable with empty defaults for optional fields
    LOGO_URL: "${LOGO_URL}"
    SPLASH: "${SPLASH}"
    SPLASH_BG: "${SPLASH_BG}"
    SPLASH_BG_COLOR: "${SPLASH_BG_COLOR}"
    SPLASH_TAGLINE: "${SPLASH_TAGLINE}"
    SPLASH_TAGLINE_COLOR: "${SPLASH_TAGLINE_COLOR}"
    SPLASH_ANIMATION: "${SPLASH_ANIMATION}"
    SPLASH_DURATION: "${SPLASH_DURATION}"

    # Bottom Menu Configuration - API configurable with empty defaults
    BOTTOMMENU_ITEMS: "${BOTTOMMENU_ITEMS}"
    BOTTOMMENU_BG_COLOR: "${BOTTOMMENU_BG_COLOR}"
    BOTTOMMENU_ICON_COLOR: "${BOTTOMMENU_ICON_COLOR}"
    BOTTOMMENU_TEXT_COLOR: "${BOTTOMMENU_TEXT_COLOR}"
    BOTTOMMENU_FONT: "${BOTTOMMENU_FONT}"
    BOTTOMMENU_FONT_SIZE: "${BOTTOMMENU_FONT_SIZE}"
    BOTTOMMENU_FONT_BOLD: "${BOTTOMMENU_FONT_BOLD}"
    BOTTOMMENU_FONT_ITALIC: "${BOTTOMMENU_FONT_ITALIC}"
    BOTTOMMENU_ACTIVE_TAB_COLOR: "${BOTTOMMENU_ACTIVE_TAB_COLOR}"
    BOTTOMMENU_ICON_POSITION: "${BOTTOMMENU_ICON_POSITION}"
    BOTTOMMENU_VISIBLE_ON: "${BOTTOMMENU_VISIBLE_ON}"

    # Firebase Configuration - API required for push notifications
    firebase_config_android: "${firebase_config_android}"
    firebase_config_ios: "${firebase_config_ios}"

    # iOS Configuration - API required for iOS builds
    APPLE_TEAM_ID: "${APPLE_TEAM_ID}"
    APNS_KEY_ID: "${APNS_KEY_ID}"
    APNS_AUTH_KEY_URL: "${APNS_AUTH_KEY_URL}"
    CERT_PASSWORD: "${CERT_PASSWORD}"
    PROFILE_URL: "${PROFILE_URL}"
    CERT_CER_URL: "${CERT_CER_URL}"
    CERT_KEY_URL: "${CERT_KEY_URL}"
    APP_STORE_CONNECT_KEY_IDENTIFIER: "${APP_STORE_CONNECT_KEY_IDENTIFIER}"
    IPHONEOS_DEPLOYMENT_TARGET: "13.0"
    COCOAPODS_PLATFORM: "ios"
    EXPORT_METHOD: "app-store"
    IS_DEVELOPMENT_PROFILE: "false"
    IS_PRODUCTION_PROFILE: "true"

    # Android Configuration - API required for Android builds
    KEY_STORE: "${KEY_STORE}"
    CM_KEYSTORE_PASSWORD: "${CM_KEYSTORE_PASSWORD}"
    CM_KEY_ALIAS: "${CM_KEY_ALIAS}"
    CM_KEY_PASSWORD: "${CM_KEY_PASSWORD}"
    COMPILE_SDK_VERSION: "35"
    MIN_SDK_VERSION: "21"
    TARGET_SDK_VERSION: "35"

    # Permissions - API configurable with secure defaults (all false unless specified)
    IS_CAMERA: "${IS_CAMERA}"
    IS_LOCATION: "${IS_LOCATION}"
    IS_MIC: "${IS_MIC}"
    IS_NOTIFICATION: "${IS_NOTIFICATION}"
    IS_CONTACT: "${IS_CONTACT}"
    IS_BIOMETRIC: "${IS_BIOMETRIC}"
    IS_CALENDAR: "${IS_CALENDAR}"
    IS_STORAGE: "${IS_STORAGE}"

    # iOS Permissions - API configurable with defaults
    IS_PHOTO_LIBRARY: "${IS_PHOTO_LIBRARY}"
    IS_PHOTO_LIBRARY_ADD: "${IS_PHOTO_LIBRARY_ADD}"
    IS_FACE_ID: "${IS_FACE_ID}"
    IS_TOUCH_ID: "${IS_TOUCH_ID}"

    # Email Configuration - Loaded from lib/scripts/email_config.sh
    # API can override these values when database is ready
    # For now, using defaults from email_config.sh
    EMAIL_CONFIG_SOURCE: "lib/scripts/email_config.sh"

scripts:
  - &debug_env
    name: Debug Environment Variables
    script: |
      #!/usr/bin/env bash
      set -e
      echo "🔍 Debugging environment variables..."

      # Function to safely print sensitive variables
      print_var() {
        local var_name=$1
        local var_value=${!var_name}
        if [[ $var_name == *"PASSWORD"* ]] || [[ $var_name == *"KEY"* ]]; then
          echo "$var_name: [REDACTED]"
        else
          echo "$var_name: $var_value"
        fi
      }

      echo "*********** App Name & Version ***********"
      print_var "APP_NAME"
      print_var "ORG_NAME"
      print_var "WEB_URL"
      print_var "VERSION_NAME"
      print_var "VERSION_CODE"
      print_var "PKG_NAME"
      print_var "BUNDLE_ID"

      echo "*********** App Customization Configuration ***********"
      print_var "IS_SPLASH"
      print_var "IS_PULLDOWN"
      print_var "IS_LOAD_IND"
      print_var "IS_BOTTOMMENU"
      print_var "IS_DEEPLINK"

      echo "*********** Push Notification Configuration ***********"
      print_var "PUSH_NOTIFY"
      print_var "IS_CHATBOT"

      echo "*********** Android Configuration ***********"
      print_var "KEY_STORE"
      print_var "CM_KEYSTORE_PASSWORD"
      print_var "CM_KEY_ALIAS"
      print_var "CM_KEY_PASSWORD"
      print_var "COMPILE_SDK_VERSION"
      print_var "MIN_SDK_VERSION"
      print_var "TARGET_SDK_VERSION"

      echo "*********** iOS Configuration ***********"
      print_var "APP_STORE_CONNECT_KEY_IDENTIFIER"
      print_var "APNS_KEY_ID"
      print_var "APPLE_TEAM_ID"
      print_var "APNS_AUTH_KEY_URL"
      print_var "IPHONEOS_DEPLOYMENT_TARGET"
      print_var "EXPORT_METHOD"

      echo "*********** Firebase Configuration ***********"
      print_var "firebase_config_android"
      print_var "firebase_config_ios"

      echo "*********** Splash Configuration ***********"
      print_var "SPLASH"
      print_var "SPLASH_BG"
      print_var "SPLASH_BG_COLOR"
      print_var "SPLASH_TAGLINE"
      print_var "SPLASH_TAGLINE_COLOR"
      print_var "SPLASH_ANIMATION"
      print_var "SPLASH_DURATION"

      echo "*********** Bottom Navigation Configuration ***********"
      print_var "BOTTOMMENU_ITEMS"
      print_var "BOTTOMMENU_BG_COLOR"
      print_var "BOTTOMMENU_ICON_COLOR"
      print_var "BOTTOMMENU_TEXT_COLOR"
      print_var "BOTTOMMENU_FONT"
      print_var "BOTTOMMENU_FONT_SIZE"
      print_var "BOTTOMMENU_FONT_BOLD"
      print_var "BOTTOMMENU_FONT_ITALIC"
      print_var "BOTTOMMENU_ACTIVE_TAB_COLOR"
      print_var "BOTTOMMENU_ICON_POSITION"
      print_var "BOTTOMMENU_VISIBLE_ON"

      echo "*********** Permissions ***********"
      print_var "IS_CAMERA"
      print_var "IS_LOCATION"
      print_var "IS_MIC"
      print_var "IS_NOTIFICATION"
      print_var "IS_CONTACT"
      print_var "IS_BIOMETRIC"
      print_var "IS_CALENDAR"
      print_var "IS_STORAGE"
      print_var "IS_PHOTO_LIBRARY"
      print_var "IS_PHOTO_LIBRARY_ADD"
      print_var "IS_FACE_ID"
      print_var "IS_TOUCH_ID"

      echo "*********** Email Configuration ***********"
      print_var "EMAIL_ID"
      print_var "SMTP_SERVER"
      print_var "SMTP_PORT"
      print_var "SMTP_USERNAME"
      print_var "SMTP_PASSWORD"

      echo "✅ Environment variables debug complete"

workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        VERSION_NAME: "${VERSION_NAME}"
        VERSION_CODE: "${VERSION_CODE}"
        APP_NAME: "${APP_NAME}"
        ORG_NAME: "${ORG_NAME}"
        WEB_URL: "${WEB_URL}"
        PKG_NAME: "${PKG_NAME}"
        BUNDLE_ID: "${BUNDLE_ID}"
        EMAIL_ID: "${EMAIL_ID}"
        API_EMAIL_ID: "${EMAIL_ID}"
        PUSH_NOTIFY: "${PUSH_NOTIFY}"
        IS_CHATBOT: "${IS_CHATBOT}"
        IS_DEEPLINK: "${IS_DEEPLINK}"
        IS_SPLASH: "${IS_SPLASH}"
        IS_PULLDOWN: "${IS_PULLDOWN}"
        IS_BOTTOMMENU: "${IS_BOTTOMMENU}"
        IS_LOAD_IND: "${IS_LOAD_IND}"
        IS_CAMERA: "${IS_CAMERA}"
        IS_LOCATION: "${IS_LOCATION}"
        IS_MIC: "${IS_MIC}"
        IS_NOTIFICATION: "${IS_NOTIFICATION}"
        IS_CONTACT: "${IS_CONTACT}"
        IS_BIOMETRIC: "${IS_BIOMETRIC}"
        IS_CALENDAR: "${IS_CALENDAR}"
        IS_STORAGE: "${IS_STORAGE}"
        LOGO_URL: "${LOGO_URL}"
        SPLASH: "${SPLASH}"
        SPLASH_BG: "${SPLASH_BG}"
        SPLASH_BG_COLOR: "${SPLASH_BG_COLOR}"
        SPLASH_TAGLINE: "${SPLASH_TAGLINE}"
        SPLASH_TAGLINE_COLOR: "${SPLASH_TAGLINE_COLOR}"
        SPLASH_ANIMATION: "${SPLASH_ANIMATION}"
        SPLASH_DURATION: "${SPLASH_DURATION}"
        BOTTOMMENU_ITEMS: "${BOTTOMMENU_ITEMS}"
        BOTTOMMENU_BG_COLOR: "${BOTTOMMENU_BG_COLOR}"
        BOTTOMMENU_ICON_COLOR: "${BOTTOMMENU_ICON_COLOR}"
        BOTTOMMENU_TEXT_COLOR: "${BOTTOMMENU_TEXT_COLOR}"
        BOTTOMMENU_FONT: "${BOTTOMMENU_FONT}"
        BOTTOMMENU_FONT_SIZE: "${BOTTOMMENU_FONT_SIZE}"
        BOTTOMMENU_FONT_BOLD: "${BOTTOMMENU_FONT_BOLD}"
        BOTTOMMENU_FONT_ITALIC: "${BOTTOMMENU_FONT_ITALIC}"
        BOTTOMMENU_ACTIVE_TAB_COLOR: "${BOTTOMMENU_ACTIVE_TAB_COLOR}"
        BOTTOMMENU_ICON_POSITION: "${BOTTOMMENU_ICON_POSITION}"
        BOTTOMMENU_VISIBLE_ON: "${BOTTOMMENU_VISIBLE_ON}"
        firebase_config_android: "${firebase_config_android}"
        firebase_config_ios: "${firebase_config_ios}"
        KEY_STORE: "${KEY_STORE}"
        CM_KEYSTORE_PASSWORD: "${CM_KEYSTORE_PASSWORD}"
        CM_KEY_ALIAS: "${CM_KEY_ALIAS}"
        CM_KEY_PASSWORD: "${CM_KEY_PASSWORD}"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Make scripts executable
        script: |
          find lib/scripts -type f -name "*.sh" -exec chmod +x {} \;
      - name: Load Admin Variables
        script: |
          source lib/scripts/android/admin_vars.sh
      - name: Run Android Build
        script: |
          bash lib/scripts/android/main.sh
    artifacts:
      - build/outputs/**/*.apk
      - build/outputs/**/*.aab

  ios-publish:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        VERSION_NAME: "${VERSION_NAME}"
        VERSION_CODE: "${VERSION_CODE}"
        APP_NAME: "${APP_NAME}"
        ORG_NAME: "${ORG_NAME}"
        WEB_URL: "${WEB_URL}"
        PKG_NAME: "${PKG_NAME}"
        BUNDLE_ID: "${BUNDLE_ID}"
        EMAIL_ID: "${EMAIL_ID}"
        PUSH_NOTIFY: "${PUSH_NOTIFY}"
        IS_CHATBOT: "${IS_CHATBOT}"
        IS_DEEPLINK: "${IS_DEEPLINK}"
        IS_SPLASH: "${IS_SPLASH}"
        IS_PULLDOWN: "${IS_PULLDOWN}"
        IS_BOTTOMMENU: "${IS_BOTTOMMENU}"
        IS_LOAD_IND: "${IS_LOAD_IND}"
        IS_CAMERA: "${IS_CAMERA}"
        IS_LOCATION: "${IS_LOCATION}"
        IS_MIC: "${IS_MIC}"
        IS_NOTIFICATION: "${IS_NOTIFICATION}"
        IS_CONTACT: "${IS_CONTACT}"
        IS_BIOMETRIC: "${IS_BIOMETRIC}"
        IS_CALENDAR: "${IS_CALENDAR}"
        IS_STORAGE: "${IS_STORAGE}"
        LOGO_URL: "${LOGO_URL}"
        SPLASH: "${SPLASH}"
        SPLASH_BG: "${SPLASH_BG}"
        SPLASH_BG_COLOR: "${SPLASH_BG_COLOR}"
        SPLASH_TAGLINE: "${SPLASH_TAGLINE}"
        SPLASH_TAGLINE_COLOR: "${SPLASH_TAGLINE_COLOR}"
        SPLASH_ANIMATION: "${SPLASH_ANIMATION}"
        SPLASH_DURATION: "${SPLASH_DURATION}"
        BOTTOMMENU_ITEMS: "${BOTTOMMENU_ITEMS}"
        BOTTOMMENU_BG_COLOR: "${BOTTOMMENU_BG_COLOR}"
        BOTTOMMENU_ICON_COLOR: "${BOTTOMMENU_ICON_COLOR}"
        BOTTOMMENU_TEXT_COLOR: "${BOTTOMMENU_TEXT_COLOR}"
        BOTTOMMENU_FONT: "${BOTTOMMENU_FONT}"
        BOTTOMMENU_FONT_SIZE: "${BOTTOMMENU_FONT_SIZE}"
        BOTTOMMENU_FONT_BOLD: "${BOTTOMMENU_FONT_BOLD}"
        BOTTOMMENU_FONT_ITALIC: "${BOTTOMMENU_FONT_ITALIC}"
        BOTTOMMENU_ACTIVE_TAB_COLOR: "${BOTTOMMENU_ACTIVE_TAB_COLOR}"
        BOTTOMMENU_ICON_POSITION: "${BOTTOMMENU_ICON_POSITION}"
        BOTTOMMENU_VISIBLE_ON: "${BOTTOMMENU_VISIBLE_ON}"
        firebase_config_android: "${firebase_config_android}"
        firebase_config_ios: "${firebase_config_ios}"
        APPLE_TEAM_ID: "${APPLE_TEAM_ID}"
        APNS_KEY_ID: "${APNS_KEY_ID}"
        APNS_AUTH_KEY_URL: "${APNS_AUTH_KEY_URL}"
        CERT_PASSWORD: "${CERT_PASSWORD}"
        PROFILE_URL: "${PROFILE_URL}"
        CERT_CER_URL: "${CERT_CER_URL}"
        CERT_KEY_URL: "${CERT_KEY_URL}"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "${APP_STORE_CONNECT_KEY_IDENTIFIER}"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Make scripts executable
        script: |
          find lib/scripts -type f -name "*.sh" -exec chmod +x {} \;
      - name: Load Admin Variables
        script: |
          source lib/scripts/ios/admin_vars.sh
      - name: Run iOS Build
        script: |
          bash lib/scripts/ios/main.sh
    artifacts:
      - build/ios/ipa/*.ipa

  combined-workflow:
    name: Combined Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        VERSION_NAME: "${VERSION_NAME}"
        VERSION_CODE: "${VERSION_CODE}"
        APP_NAME: "${APP_NAME}"
        ORG_NAME: "${ORG_NAME}"
        WEB_URL: "${WEB_URL}"
        PKG_NAME: "${PKG_NAME}"
        BUNDLE_ID: "${BUNDLE_ID}"
        EMAIL_ID: "${EMAIL_ID}"
        PUSH_NOTIFY: "${PUSH_NOTIFY}"
        IS_CHATBOT: "${IS_CHATBOT}"
        IS_DEEPLINK: "${IS_DEEPLINK}"
        IS_SPLASH: "${IS_SPLASH}"
        IS_PULLDOWN: "${IS_PULLDOWN}"
        IS_BOTTOMMENU: "${IS_BOTTOMMENU}"
        IS_LOAD_IND: "${IS_LOAD_IND}"
        IS_CAMERA: "${IS_CAMERA}"
        IS_LOCATION: "${IS_LOCATION}"
        IS_MIC: "${IS_MIC}"
        IS_NOTIFICATION: "${IS_NOTIFICATION}"
        IS_CONTACT: "${IS_CONTACT}"
        IS_BIOMETRIC: "${IS_BIOMETRIC}"
        IS_CALENDAR: "${IS_CALENDAR}"
        IS_STORAGE: "${IS_STORAGE}"
        LOGO_URL: "${LOGO_URL}"
        SPLASH: "${SPLASH}"
        SPLASH_BG: "${SPLASH_BG}"
        SPLASH_BG_COLOR: "${SPLASH_BG_COLOR}"
        SPLASH_TAGLINE: "${SPLASH_TAGLINE}"
        SPLASH_TAGLINE_COLOR: "${SPLASH_TAGLINE_COLOR}"
        SPLASH_ANIMATION: "${SPLASH_ANIMATION}"
        SPLASH_DURATION: "${SPLASH_DURATION}"
        BOTTOMMENU_ITEMS: "${BOTTOMMENU_ITEMS}"
        BOTTOMMENU_BG_COLOR: "${BOTTOMMENU_BG_COLOR}"
        BOTTOMMENU_ICON_COLOR: "${BOTTOMMENU_ICON_COLOR}"
        BOTTOMMENU_TEXT_COLOR: "${BOTTOMMENU_TEXT_COLOR}"
        BOTTOMMENU_FONT: "${BOTTOMMENU_FONT}"
        BOTTOMMENU_FONT_SIZE: "${BOTTOMMENU_FONT_SIZE}"
        BOTTOMMENU_FONT_BOLD: "${BOTTOMMENU_FONT_BOLD}"
        BOTTOMMENU_FONT_ITALIC: "${BOTTOMMENU_FONT_ITALIC}"
        BOTTOMMENU_ACTIVE_TAB_COLOR: "${BOTTOMMENU_ACTIVE_TAB_COLOR}"
        BOTTOMMENU_ICON_POSITION: "${BOTTOMMENU_ICON_POSITION}"
        BOTTOMMENU_VISIBLE_ON: "${BOTTOMMENU_VISIBLE_ON}"
        firebase_config_android: "${firebase_config_android}"
        firebase_config_ios: "${firebase_config_ios}"
        APPLE_TEAM_ID: "${APPLE_TEAM_ID}"
        APNS_KEY_ID: "${APNS_KEY_ID}"
        APNS_AUTH_KEY_URL: "${APNS_AUTH_KEY_URL}"
        CERT_PASSWORD: "${CERT_PASSWORD}"
        PROFILE_URL: "${PROFILE_URL}"
        CERT_CER_URL: "${CERT_CER_URL}"
        CERT_KEY_URL: "${CERT_KEY_URL}"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "${APP_STORE_CONNECT_KEY_IDENTIFIER}"
        KEY_STORE: "${KEY_STORE}"
        CM_KEYSTORE_PASSWORD: "${CM_KEYSTORE_PASSWORD}"
        CM_KEY_ALIAS: "${CM_KEY_ALIAS}"
        CM_KEY_PASSWORD: "${CM_KEY_PASSWORD}"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Make scripts executable
        script: |
          find lib/scripts -type f -name "*.sh" -exec chmod +x {} \;
      - name: Load Admin Variables
        script: |
          source lib/scripts/combined/admin_vars.sh
      - name: Run Combined Build
        script: |
          bash lib/scripts/combined/main.sh
    artifacts:
      - build/**/outputs/flutter-apk/*.apk
      - build/**/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa
